insert into t_sys_code(codeId, codeDetailId, codeName, codeDetailName) values('COM001', '0', 'Sex', 'Male');
insert into t_sys_code(codeId, codeDetailId, codeName, codeDetailName) values('COM001', '1', 'Sex', 'Female');
insert into t_sys_code(codeId, codeDetailId, codeName, codeDetailName) values('COM002', '0', 'Sign Status', 'Sign Out');
insert into t_sys_code(codeId, codeDetailId, codeName, codeDetailName) values('COM002', '1', 'Sign Status', 'Sign In');
insert into t_sys_code(codeId, codeDetailId, codeName, codeDetailName) values('COM003', '0', 'Expenses Status', 'Temporal Save');
insert into t_sys_code(codeId, codeDetailId, codeName, codeDetailName) values('COM003', '1', 'Expenses Status', 'Application');
insert into t_sys_code(codeId, codeDetailId, codeName, codeDetailName) values('COM003', '2', 'Expenses Status', 'Pending');
insert into t_sys_code(codeId, codeDetailId, codeName, codeDetailName) values('COM003', '3', 'Expenses Status', 'Reject');
insert into t_sys_code(codeId, codeDetailId, codeName, codeDetailName) values('COM003', '4', 'Expenses Status', 'Approved');
insert into t_sys_code(codeId, codeDetailId, codeName, codeDetailName) values('COM003', '5', 'Expenses Status', 'Finish');
insert into t_sys_code(codeId, codeDetailId, codeName, codeDetailName) values('COM004', '1', 'Travel Local Type', 'Domestic');
insert into t_sys_code(codeId, codeDetailId, codeName, codeDetailName) values('COM004', '2', 'Travel Local Type', 'Hong Kong, Macao And Taiwan');
insert into t_sys_code(codeId, codeDetailId, codeName, codeDetailName) values('COM004', '3', 'Travel Local Type', 'Overseas other than Great China');
insert into t_sys_code(codeId, codeDetailId, codeName, codeDetailName) values('COM005', '1', 'Workflow Process Status', 'Todo');
insert into t_sys_code(codeId, codeDetailId, codeName, codeDetailName) values('COM005', '2', 'Workflow Process Status', 'Approved');
insert into t_sys_code(codeId, codeDetailId, codeName, codeDetailName) values('COM005', '3', 'Workflow Process Status', 'Reject');
